// Code generated by protoc-gen-go. DO NOT EDIT.
// source: calc/calcpb/calc.proto

package calcpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Calc struct {
	FirstNumber          int32    `protobuf:"varint,1,opt,name=first_number,json=firstNumber,proto3" json:"first_number,omitempty"`
	SecondNumber         int32    `protobuf:"varint,2,opt,name=second_number,json=secondNumber,proto3" json:"second_number,omitempty"`
	TotalNumber          int32    `protobuf:"varint,3,opt,name=total_number,json=totalNumber,proto3" json:"total_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Calc) Reset()         { *m = Calc{} }
func (m *Calc) String() string { return proto.CompactTextString(m) }
func (*Calc) ProtoMessage()    {}
func (*Calc) Descriptor() ([]byte, []int) {
	return fileDescriptor_calc_c9f0cf166060d963, []int{0}
}
func (m *Calc) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Calc.Unmarshal(m, b)
}
func (m *Calc) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Calc.Marshal(b, m, deterministic)
}
func (dst *Calc) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Calc.Merge(dst, src)
}
func (m *Calc) XXX_Size() int {
	return xxx_messageInfo_Calc.Size(m)
}
func (m *Calc) XXX_DiscardUnknown() {
	xxx_messageInfo_Calc.DiscardUnknown(m)
}

var xxx_messageInfo_Calc proto.InternalMessageInfo

func (m *Calc) GetFirstNumber() int32 {
	if m != nil {
		return m.FirstNumber
	}
	return 0
}

func (m *Calc) GetSecondNumber() int32 {
	if m != nil {
		return m.SecondNumber
	}
	return 0
}

func (m *Calc) GetTotalNumber() int32 {
	if m != nil {
		return m.TotalNumber
	}
	return 0
}

type CalcRequest struct {
	Calc                 *Calc    `protobuf:"bytes,1,opt,name=calc,proto3" json:"calc,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CalcRequest) Reset()         { *m = CalcRequest{} }
func (m *CalcRequest) String() string { return proto.CompactTextString(m) }
func (*CalcRequest) ProtoMessage()    {}
func (*CalcRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_calc_c9f0cf166060d963, []int{1}
}
func (m *CalcRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CalcRequest.Unmarshal(m, b)
}
func (m *CalcRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CalcRequest.Marshal(b, m, deterministic)
}
func (dst *CalcRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CalcRequest.Merge(dst, src)
}
func (m *CalcRequest) XXX_Size() int {
	return xxx_messageInfo_CalcRequest.Size(m)
}
func (m *CalcRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CalcRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CalcRequest proto.InternalMessageInfo

func (m *CalcRequest) GetCalc() *Calc {
	if m != nil {
		return m.Calc
	}
	return nil
}

type CalcResponse struct {
	Result               int32    `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Answer               bool     `protobuf:"varint,2,opt,name=answer,proto3" json:"answer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CalcResponse) Reset()         { *m = CalcResponse{} }
func (m *CalcResponse) String() string { return proto.CompactTextString(m) }
func (*CalcResponse) ProtoMessage()    {}
func (*CalcResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_calc_c9f0cf166060d963, []int{2}
}
func (m *CalcResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CalcResponse.Unmarshal(m, b)
}
func (m *CalcResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CalcResponse.Marshal(b, m, deterministic)
}
func (dst *CalcResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CalcResponse.Merge(dst, src)
}
func (m *CalcResponse) XXX_Size() int {
	return xxx_messageInfo_CalcResponse.Size(m)
}
func (m *CalcResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CalcResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CalcResponse proto.InternalMessageInfo

func (m *CalcResponse) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

func (m *CalcResponse) GetAnswer() bool {
	if m != nil {
		return m.Answer
	}
	return false
}

func init() {
	proto.RegisterType((*Calc)(nil), "calc.Calc")
	proto.RegisterType((*CalcRequest)(nil), "calc.CalcRequest")
	proto.RegisterType((*CalcResponse)(nil), "calc.CalcResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CalcServiceClient is the client API for CalcService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CalcServiceClient interface {
	Calc(ctx context.Context, in *CalcRequest, opts ...grpc.CallOption) (*CalcResponse, error)
}

type calcServiceClient struct {
	cc *grpc.ClientConn
}

func NewCalcServiceClient(cc *grpc.ClientConn) CalcServiceClient {
	return &calcServiceClient{cc}
}

func (c *calcServiceClient) Calc(ctx context.Context, in *CalcRequest, opts ...grpc.CallOption) (*CalcResponse, error) {
	out := new(CalcResponse)
	err := c.cc.Invoke(ctx, "/calc.CalcService/Calc", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CalcServiceServer is the server API for CalcService service.
type CalcServiceServer interface {
	Calc(context.Context, *CalcRequest) (*CalcResponse, error)
}

func RegisterCalcServiceServer(s *grpc.Server, srv CalcServiceServer) {
	s.RegisterService(&_CalcService_serviceDesc, srv)
}

func _CalcService_Calc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalcRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalcServiceServer).Calc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calc.CalcService/Calc",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalcServiceServer).Calc(ctx, req.(*CalcRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CalcService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "calc.CalcService",
	HandlerType: (*CalcServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Calc",
			Handler:    _CalcService_Calc_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "calc/calcpb/calc.proto",
}

func init() { proto.RegisterFile("calc/calcpb/calc.proto", fileDescriptor_calc_c9f0cf166060d963) }

var fileDescriptor_calc_c9f0cf166060d963 = []byte{
	// 223 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0xb1, 0x4f, 0x85, 0x30,
	0x10, 0xc6, 0x7d, 0xfa, 0x24, 0x2f, 0x47, 0x1d, 0xec, 0xf0, 0x62, 0x1c, 0x8c, 0x0f, 0x17, 0x17,
	0x21, 0xc1, 0x9d, 0x41, 0x77, 0x07, 0xdc, 0x5c, 0x4c, 0xa9, 0x67, 0x42, 0x52, 0x5b, 0x68, 0x8b,
	0xfe, 0xfb, 0xa6, 0x77, 0x25, 0x61, 0x81, 0xde, 0x97, 0x5f, 0xfa, 0xfd, 0x7a, 0x70, 0xd4, 0xca,
	0xe8, 0x26, 0x7d, 0xa6, 0x81, 0x7e, 0xf5, 0xe4, 0x5d, 0x74, 0x72, 0x9f, 0xce, 0xd5, 0x0c, 0xfb,
	0x57, 0x65, 0xb4, 0x3c, 0x81, 0xf8, 0x1e, 0x7d, 0x88, 0x9f, 0x76, 0xf9, 0x19, 0xd0, 0xdf, 0xec,
	0xee, 0x77, 0x8f, 0x97, 0x7d, 0x49, 0xd9, 0x1b, 0x45, 0xf2, 0x01, 0xae, 0x02, 0x6a, 0x67, 0xbf,
	0x56, 0xe6, 0x9c, 0x18, 0xc1, 0x61, 0x86, 0x4e, 0x20, 0xa2, 0x8b, 0xca, 0xac, 0xcc, 0x05, 0xdf,
	0x43, 0x19, 0x23, 0xd5, 0x13, 0x94, 0xa9, 0xb2, 0xc7, 0x79, 0xc1, 0x10, 0xe5, 0x1d, 0x90, 0x09,
	0x35, 0x96, 0x2d, 0xd4, 0xa4, 0x48, 0x00, 0x1b, 0x76, 0x20, 0x18, 0x0f, 0x93, 0xb3, 0x01, 0xe5,
	0x11, 0x0a, 0x8f, 0x61, 0x31, 0x31, 0x3b, 0xe6, 0x29, 0xe5, 0xca, 0x86, 0xbf, 0xec, 0x75, 0xe8,
	0xf3, 0xd4, 0x76, 0x5c, 0xf7, 0x8e, 0xfe, 0x77, 0xd4, 0x28, 0x9b, 0xfc, 0xe0, 0xeb, 0x4d, 0x11,
	0x9b, 0xdc, 0xca, 0x6d, 0xc4, 0x6d, 0xd5, 0xd9, 0xcb, 0xe1, 0xa3, 0xe0, 0xe5, 0x0d, 0x05, 0x2d,
	0xee, 0xf9, 0x3f, 0x00, 0x00, 0xff, 0xff, 0x2f, 0x42, 0xa9, 0x18, 0x52, 0x01, 0x00, 0x00,
}
